services:
  acesso_apply_test:
    image: acesso_apply_test
    container_name: acesso_apply_test
    build: .
    expose: 
      - 3000
    ports:
      - 3000:3000
    links:
      - mongodb
    # environment:
    #   - MONGO_URL=mongodb://mongo:27017/
    
    # command: yarn dev
  # accounts:
  #   image: baldini/testacesso
  #   ports:
  #     - 5000:80
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
